spring:
  data:
    mongodb:
      uri: mongodb://java_test:java_test@120.48.107.224:27017,120.48.107.224:27018/java_test?replicaSet=ftc&authSource=java_test&readPreference=secondaryPreferred&connectTimeoutMS=60000
